apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: loadbalancer
  selector:
    app: todo
  type: LoadBalancer
